// COLORS
export const MAIN_BG_COLOR = '#14133D'
export const SECONDARY_BG_COLOR = '#ADD8E6'
export const TEXT_COLOR =  '#14133D'
export const TEXT_CONTRAST =  '#FFFFFF'
export const INPUT_BG_COLOR =  '#FFFFFF'
export const BUTTON_COLOR =  '#FFFFFF'
export const INPUT_TEXT_COLOR = '#86ACD9'
export const BORDER_COLOR = '#0BA5D3'
export const DISABLED_COLOR = '#bdbdbd'
export const SELECT_BG_COLOR =  '#FFFFFF'
export const WARN_COLOR = '#FFA500'
export const ICON_BG_COLOR = '#0BA5D3'
export const EVEN_ROW_COLOR = '#ADD8E6'
export const DEFAULT_BG_COLOR =  '#FFFFFF'
export const ERROR_COLOR = '#FF0000'

// SIZES AND SPACING
export const INPUT_FONT_SIZE = '18px'
export const SELECT_FONT_SIZE = '18px'
export const DEFAULT_FONT_SIZE = '18px'
export const BUTTON_PADDING = '13px'
export const INPUT_PADDING = '10px'
export const SELECT_PADDING = '10px'
export const INPUT_HEIGHT = '1.5rem'
export const SELECT_HEIGHT = '2.8rem'
export const BUTTON_FONT_SIZE = '1rem'
export const DEFAULT_SPACING = '1rem'
export const LARGE_SPACING = '2rem'
export const LARGE_FONT = '1.5rem'
export const BUTTON_RADIUS = '5px'
export const INPUT_BORDER_RADIUS = '4px'
export const STD_ICON_SIZE = 45
export const S_ICON_SIZE = 25